name: client_information
description: This is a plugin that lets you get the basic information from your application's client. It's easy to use and supports different platforms (Android, iOS, and Web).
version: 3.1.0
homepage: https://github.com/Kent1011/client_information

environment:  
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  uuid: ">=4.5.1 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: kent.chien.client_information
        pluginClass: ClientInformationPlugin
      ios:
        pluginClass: ClientInformationPlugin
      web:
        pluginClass: ClientInformationWeb
        fileName: client_information_web.dart
